version: '3'

services:
    backend:
        build: /api
        ports:
          - 5001:80
        environment:
          - USERNAME_DB=${USERNAME_DB}
          - PASSWORD_DB=${PASSWORD_DB}
        depends_on:
          db:
            condition: service_healthy
        volumes:
          - ./api/code:/code
    db:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'db'
        MYSQL_USER: "${USERNAME_DB}"
        MYSQL_PASSWORD: "${PASSWORD_DB}"
        MYSQL_ROOT_PASSWORD: "${PASSWORD_DB}"
      ports:
        - '3306:3306'
      expose:
        - '3306'
      volumes:
        - ./db/data:/var/lib/mysql:rw
        - ./db/init:/docker-entrypoint-initdb.d/:rw
      healthcheck:
        test: ["CMD", "mysqladmin", "--password=${PASSWORD_DB}", "ping", "-h", "localhost"]
        timeout: 20s
        retries: 3